Add FarmActivity.kt
AliaksandrG/homework pull request #4
Opened 2020-09-30 12:41 UTC by AliaksandrG

![image](https://user-images.githubusercontent.com/70669501/94686366-67864400-0333-11eb-977f-07174720ff45.png)

2020-09-30 14:13 UTC, stasenkots requested changes
You should use ViewModel in the task.And coroutines for emulating "receiving some data from server".also better to group repeated logic

2020-09-30 14:13 UTC, stasenkots commented on app/src/main/java/com/example/myapplication/FarmActivity.kt
> +    private fun isHarvest() = runBlocking<Unit> {
don't use runBlocking

2020-10-01 09:30 UTC, AliaksandrG commented on app/src/main/java/com/example/myapplication/FarmActivity.kt
> +    private fun isHarvest() = runBlocking<Unit> {
fixed

2020-10-01 09:48 UTC, stasenkots approved these changes

2020-10-01 12:13 UTC, PolzaAnt approved these changes

2020-10-01 19:25 UTC, TMSlebedev approved these changes
Fix selected and merge

2020-10-01 19:25 UTC, TMSlebedev commented on app/src/main/java/com/example/myapplication/FarmActivity.kt
> +        val viewModel: MyCountryModel by lazy {
nice

2020-10-01 19:25 UTC, TMSlebedev commented on app/src/main/java/com/example/myapplication/FarmActivity.kt
> +            CountryObject.Gomel.cabbage.value = 0
use postValue

2020-10-01 19:25 UTC, TMSlebedev commented on app/src/main/java/com/example/myapplication/countryModel/MyCountryModel.kt
> +                    if (country.potato.value!! == 100
don't use asser calls '!!' use safe requests with '?'

2020-10-01 19:25 UTC, TMSlebedev commented on app/src/main/res/layout/activity_farm.xml
> +
delete empty

2020-10-01 19:25 UTC, TMSlebedev commented on app/src/main/res/layout/activity_main.xml
> +        android:text="homework 20"
add to Strings

2020-10-01 21:18 UTC, merged